drama_movies={"baddayatblackrock_dialog.txt" : {"title" : "Bad Day at Black Rock", "characters":["MACREEDY", "SMITH", "LIZ", "HORN", "DOC"], "villain": ["HECTOR"], "year":1995},
"blackdahliathe_dialog.txt" : {"title" : "Black Dahlia", "characters":["BUCKY", "KAY", "LEE", "MADELEINE", "ELIZABETH SHORT"], "villain": ["RAMONA"], "year":2006},
"bloodsimple_dialog.txt" : {"title" : "Blood Simple", "characters":["MARTY", "ABBY", "RAY", "MEURICE", "DEBRA"], "villain": ["VISSER"], "year":1984},
"bonnieandclyde_dialog.txt" : {"title" : "Bonnie and Clyde", "characters":["C.W.", "BUCK", "HAMER", "BLANCE", "VELMA"], "villain": ["BONNIE","CLYDE"], "year":1967},
"changeling_dialog.txt" : {"title" : "Changeling", "characters":["CHRISTINE", "WALTER", "OPERATOR", "MR. HARRIS"], "villain": ["GORDEN"], "year":2008},
"enemyofthestate_dialog.txt" : {"title" : "Enemy of the State", "characters":["DEAN", "RACHEL", "SENATOR ALBERT", "CHRISTA", "HICKS"], "villain": ["REYNOLDS"], "year":1998},
"insomnia_dialog.txt" : {"title" : "Insomnia", "characters":["WILL", "HAP", "PILOT", "ELLIE", "CHIEF NYBACK"], "villain": ["WALTER"], "year":2002},
"laconfidential_dialog.txt" : {"title" : "L.A. Confidential", "characters":["JACK", "EXLEY", "BUD", "LYNN", "HUDGEONS"], "villain": ["DUDLEY"], "year":1997},
"se7en_dialog.txt" : {"title" : "Se7en", "characters":["SOMERSET", "MILLS", "TRACY", "DAVIS", "O'NEILL"], "villain": ["JOHN DOE"], "year":1995},
"someonetowatchoverme_dialog.txt" : {"title" : "Someone to Watch Over Me", "characters": ["CLAIRE", "MIKE", "ELLIE", "GARBER", "NEIL"], "villain": ["VENZA"], "year":1987},
"twinpeaks_dialog.txt" : {"title" : "Twin Peaks", "characters":["LAURA", "LELAND", "RONETTE", "SHELLY", "JEFFRIES"], "villain": ["BOB"], "year":1992},
"afewgoodmen_dialog.txt" : {"title" : "A Few Good Men", "characters":["KAFFEE", "JO", "ROSS", "SAM", "DOWNEY"], "villain": ["JESSEP"], "year":1992},
"truegrit_dialog.txt" : {"title" : "True Grit", "characters":["Mattie", "LeBoeuf", "Rooster", "Lucky Ned", "Stonehill"], "villain": ["Chaney"], "year":2009},
"takinglives_dialog.txt" : {"title" : "Taking Lives", "characters":["COSTA", "GRACE", "MRS. ASHER", "DIRECTOR GILLET", "DAN"], "villain": ["ASHER"], "year":2003},
"minisfirsttime_dialog.txt" : {"title" : "Mini's First Time", "characters":["DIANE", "RUDELL", "JEANETTE", "TROY", "KAYLA"], "villain": ["MINI","MARTIN"], "year":2006},
"metro_dialog.txt" : {"title" : "Metro", "characters":["ROPER", "MCCALL", "FORBES", "KIMURA", "BAFFERT"], "villain": ["KORDA"], "year":1997},
"manhunter_dialog.txt" : {"title" : "Manhunter", "characters":["GRAHAM", "MOLLY", "REBA", "LECKTOR", "CRAWFORD"], "villain": ["DOLLARHYDE"], "year":1984},
"klute_dialog.txt" : {"title" : "Klute", "characters":["BREE", "KLUTE", "TRASK", "FRANK", "ARLYN"], "villain": ["CABLE"], "year":1971},
"americangangster_dialog.txt" : {"title" : "American Gangster", "characters":["RICHIE", "LAURIE", "TRUPO", "RIVERA", "TOBACK"], "villain": ["FRANK"], "year":2007},
"backdraft_dialog.txt":{"title" : "Backdraft", "characters":["STEPHEN", "BRIAN", "SWAYZAK", "SHADOW", "RICCO"], "villain": ["AXE"], "year":1991},
"bluevelvet_dialog.txt" : {"title" : "Blue Velvet", "characters":["JEFFREY", "SANDY", "DETECTIVE WILLIAMS", "DOROTHY", "YELLOW MAN"], "villain": ["FRANK"], "year":1986},
"brick_dialog.txt" : {"title" : "Brick", "characters":["BRENDAN", "EMILY", "THE BRAIN", "PIN"], "villain": ["LAURA", "TUGGER" ], "year":2005},
"charade_dialog.txt" : {"title" : "Charade", "characters":["REGGIE", "SYLVIE", "CHARLES","CRUIKSHANK", 'ADAM'], "villain": ["BARTHOLOMEW", 'CARSON'], "year":1963},
"copycat_dialog.txt" : {"title" : "Copycat", "characters":["HELEN", "SUSAN", "M.J.", "RUBEN", "SAKS"], "villain": ["PETER"], "year":1995},
"fridaythe13th_dialog.txt" : {"title" : "Friday the 13th", "characters":["JACK", "BILL", "ALICE", "NED", "MARCIE"], "villain": ["MRS. VOORHEES"], "year":1980},
"jennifereight_dialog.txt" : {"title" : "Jennifer Eight", "characters":["BERLIN", "St ANNE", "HELENA", "ROSS", 'MARGIE'], "villain": ["TAYLOR"], "year":1992},
"manhattanmurdermystery_dialog.txt" : {"title" : "Manhattan Murder Mystery", "characters":["LARRY", "CAROL", "LILLIAN", "HELEN",'MARCIA','TED'], "villain": ["PAUL"], "year":1993},
"sherlockholmes_dialog.txt" : {"title" : "Sherlock Holmes", "characters":["HOLMES", "WATSON", "LESTRADE", "MARY", "DREDGER"], "villain": ['IRENE','MORIARY'], "year":2008}
}

